//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BalderTestApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Meshes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Meshes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BalderTestApplication.Meshes", typeof(Meshes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3DSMAX_ASCIIEXPORT	200
        ///*COMMENT &quot;AsciiExport Version  2,00 - Sun Jul 08 19:59:52 2007&quot;
        ///*SCENE {
        ///	*SCENE_FILENAME &quot;&quot;
        ///	*SCENE_FIRSTFRAME 0
        ///	*SCENE_LASTFRAME 100
        ///	*SCENE_FRAMESPEED 30
        ///	*SCENE_TICKSPERFRAME 160
        ///	*SCENE_BACKGROUND_STATIC 0.0000	0.0000	0.0000
        ///	*SCENE_AMBIENT_STATIC 0.0000	0.0000	0.0000
        ///}
        ///*MATERIAL_LIST {
        ///	*MATERIAL_COUNT 0
        ///}
        ///*GEOMOBJECT {
        ///	*NODE_NAME &quot;Text01&quot;
        ///	*NODE_TM {
        ///		*NODE_NAME &quot;Text01&quot;
        ///		*INHERIT_POS 0 0 0
        ///		*INHERIT_ROT 0 0 0
        ///		*INHERIT_SCL 0 0 0
        ///		*TM_ROW0 1.0000	0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string asteroids {
            get {
                return ResourceManager.GetString("asteroids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3DSMAX_ASCIIEXPORT	200
        ///*COMMENT &quot;AsciiExport Version  2,00 - Sun Jul 08 21:04:29 2007&quot;
        ///*SCENE {
        ///	*SCENE_FILENAME &quot;henga.max&quot;
        ///	*SCENE_FIRSTFRAME 0
        ///	*SCENE_LASTFRAME 100
        ///	*SCENE_FRAMESPEED 30
        ///	*SCENE_TICKSPERFRAME 160
        ///	*SCENE_BACKGROUND_STATIC 0.3686	0.5294	0.5882
        ///	*SCENE_AMBIENT_STATIC 0.1922	0.1922	0.1922
        ///}
        ///*MATERIAL_LIST {
        ///	*MATERIAL_COUNT 1
        ///	*MATERIAL 0 {
        ///		*MATERIAL_NAME &quot;henga&quot;
        ///		*MATERIAL_CLASS &quot;Standard&quot;
        ///		*MATERIAL_AMBIENT 0.6039	0.6039	0.6039
        ///		*MATERIAL_DIFFUSE 0.6039	0.6039	0.603 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string henga {
            get {
                return ResourceManager.GetString("henga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3DSMAX_ASCIIEXPORT	200
        ///*COMMENT &quot;AsciiExport Version  2,00 - Sun Jul 08 19:57:40 2007&quot;
        ///*SCENE {
        ///	*SCENE_FILENAME &quot;&quot;
        ///	*SCENE_FIRSTFRAME 0
        ///	*SCENE_LASTFRAME 100
        ///	*SCENE_FRAMESPEED 30
        ///	*SCENE_TICKSPERFRAME 160
        ///	*SCENE_BACKGROUND_STATIC 0.0000	0.0000	0.0000
        ///	*SCENE_AMBIENT_STATIC 0.0000	0.0000	0.0000
        ///}
        ///*MATERIAL_LIST {
        ///	*MATERIAL_COUNT 0
        ///}
        ///*GEOMOBJECT {
        ///	*NODE_NAME &quot;Sphere01&quot;
        ///	*NODE_TM {
        ///		*NODE_NAME &quot;Sphere01&quot;
        ///		*INHERIT_POS 0 0 0
        ///		*INHERIT_ROT 0 0 0
        ///		*INHERIT_SCL 0 0 0
        ///		*TM_ROW0 1.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rock {
            get {
                return ResourceManager.GetString("rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3DSMAX_ASCIIEXPORT	200
        ///*COMMENT &quot;AsciiExport Version  2,00 - Sat May 19 00:12:52 2007&quot;
        ///*SCENE {
        ///	*SCENE_FILENAME &quot;&quot;
        ///	*SCENE_FIRSTFRAME 0
        ///	*SCENE_LASTFRAME 100
        ///	*SCENE_FRAMESPEED 30
        ///	*SCENE_TICKSPERFRAME 160
        ///	*SCENE_BACKGROUND_STATIC 0.0000	0.0000	0.0000
        ///	*SCENE_AMBIENT_STATIC 0.0000	0.0000	0.0000
        ///}
        ///*MATERIAL_LIST {
        ///	*MATERIAL_COUNT 0
        ///}
        ///*GEOMOBJECT {
        ///	*NODE_NAME &quot;Sphere01&quot;
        ///	*NODE_TM {
        ///		*NODE_NAME &quot;Sphere01&quot;
        ///		*INHERIT_POS 0 0 0
        ///		*INHERIT_ROT 0 0 0
        ///		*INHERIT_SCL 0 0 0
        ///		*TM_ROW0 1.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sphere {
            get {
                return ResourceManager.GetString("sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *3DSMAX_ASCIIEXPORT	200
        ///*COMMENT &quot;AsciiExport Version  2,00 - Sat May 19 02:36:04 2007&quot;
        ///*SCENE {
        ///	*SCENE_FILENAME &quot;sphere.max&quot;
        ///	*SCENE_FIRSTFRAME 0
        ///	*SCENE_LASTFRAME 100
        ///	*SCENE_FRAMESPEED 30
        ///	*SCENE_TICKSPERFRAME 160
        ///	*SCENE_BACKGROUND_STATIC 0.0000	0.0000	0.0000
        ///	*SCENE_AMBIENT_STATIC 0.0000	0.0000	0.0000
        ///}
        ///*MATERIAL_LIST {
        ///	*MATERIAL_COUNT 0
        ///}
        ///*GEOMOBJECT {
        ///	*NODE_NAME &quot;Teapot01&quot;
        ///	*NODE_TM {
        ///		*NODE_NAME &quot;Teapot01&quot;
        ///		*INHERIT_POS 0 0 0
        ///		*INHERIT_ROT 0 0 0
        ///		*INHERIT_SCL 0 0 0
        ///		*TM_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string teapot {
            get {
                return ResourceManager.GetString("teapot", resourceCulture);
            }
        }
    }
}
